# Experimental Designs


## Designs in Categorical Data Analysis

Studies in Categorical Data Analysis can be classified into several designs.  These designs fall into the following two categories:

1. _Retrospective Design_: looks at and analyzes measurements that have already been taken.
2. _Prospective Design_: specifies the measurements to be collected at a future time.  

### Case Control Study

In case control studies, the marginal distribution of the _response variable_ is fixed by the sampling design.  In other words, researchers select particular numbers of each category of the response variable in order to ensure that enough of each case are included in the sample.  The result is that the marginal distribution of the response is non-random.

Unfortunately, in order to calculate conditional probabilities, the marginal distribution of interest must be random.  The difference of proportions for the response and the relative risk are both based on the marginal distribution of the response, and are both invalid procedures in case-control studies.

In taking the measurements, researchers idenitfy people who are already classified into the response variable, making the design retrospective.

### Cross Sectional Study


### Cohort Study

In Cohort Studies, subjects make their own choice about which group in the explanatory variable to join and researchers monitor the subjects with respect to a response variable over a period of time.  Both the explanatory and response variables are random and only the total sample size is fixed by the researcher.  Thus, conditional probabilities may be computed for both the predictor and response variables; differences in proportions may be estimated; and the relative risk is defined for the response variable.

Since subjects select the group in which they will be and a measurement of their response is taken later, cohort studies are prospective.

### Randomized Study

In randomized Studies, the researcher randomly assigns subjects to the explanatory variable and then observes their response (making this a prospective study).  The marginal distribution of the explanatory variable is therefore fixed, and conditional probabilities may not be computed.

The response variable, on the other hand, is random and conditional probabilites may be computed, as well as the difference of proportions and relative risk.


### Summary of Designs

```{r, echo = FALSE, results = 'asis'}
data.frame(type = c("", "", "", "Case Control", 
                    "Cross-Sectional", "Cohort", "Randomized"),
           col2 = c("conditional", "probability", "explanatory",
                    "xxx", "xxx", "xxx", ""),
           col3 = c("conditional", "probability", "response",
                    "", "xxx", "xxx", "xxx"),
           col4 = c("", "difference of", "proportions", "",
                    "xxx", "xxx", "xxx"),
           col5 = c("", "Relative", "Risk", "",
                    "xxx", "xxx", "xxx"),
           col6 = c("", "Odds", "Ratio", 
                    "xxx", "xxx", "xxx", "xxx"),
           stringsAsFactors = FALSE) %>%
  dust(bookdown = TRUE) %>%
  sprinkle_colnames("", "", "", "", "", "") %>%
  sprinkle(pad = 3) %>%
  sprinkle(rows = 1, 
           border = "top") %>%
  sprinkle(rows = c(3:7), 
           border = "bottom")
```
