# Gamma Function

The Gamma Function is a function used frequently in statistical theory. It has properties that permit simplified calculations and is used in defining many probability distributions, particularly within the Exponential family of distributions.

## Definition {#gamma-function-definition}

$$\Gamma(x) = \int\limits_0^{\infty}t^{x-1}e^{-t}dt$$

Note that the definition defines a function of $x$ that is integrated over $t$.  Thus, for each value of $x$, a curve is defined, and the Gamma function calculates the area under the curve defined by $x$.

## Theorems for the Gamma Function

### Lemma {#gamma-function-reduction-lemma}

$$\left[ -t^{x-1} e^{-t} \right]_{t = 0}^{t = \infty} = 0$$

_Proof:_

$$\begin{aligned}
\left[ -t^{x-1} e^{-t} \right]_{t = 0}^{t = \infty}
 &= \lim_{t\to\infty}\big(-t^{x - 1} e^{-t}\big) - 
       0^{x - 1} e^{-0} \\
 &= \lim_{t\to\infty}\big(-t^{x - 1} e^{-t}\big) - 0 \\
 &= \lim_{t\to\infty}\big(-t^{x - 1} e^{-t}\big) \\
 &= - \lim_{t\to\infty}\frac{t^{x - 1}}{e^t} \\
 &= - \lim_{t\to\infty} \left\{exp\left[ (x - 1) \ln t - t\right] \right\} \\
 &= - \lim_{t\to\infty} \left\{ exp \left[(x - 1) \cdot t \cdot \Big( \frac{\ln t}{t} - 1\Big) \right]\right\} \\
^{[1]} &= \lim_{t\to\infty} \left\{ exp \left[(x - 1) \cdot t \cdot \Big( 0 - 1\Big) \right]\right\} \\
&= \lim_{t\to\infty} \left\{ exp \left[- (x - 1) \cdot t \right]\right\} \\
 &= \lim_{t\to\infty} \frac{1}{e^{(x - 1) \cdot t}} \\
 &= 0
\end{aligned}$$

> 1.  L'H\^{o}pital's Rule: $\lim_{x\to u}\frac{f(x)}{g(x)} = \lim_{x\to u} \frac{f'(x)}{g'(x)}$. This implies $\lim_{x\to \infty} \frac{\ln x}{x} = \lim_{x\to \infty} \frac{\frac{1}{x}}{1} = \lim_{x \to \infty} \frac{1}{x} = 0$

### Theorem: The Reduction Relation {#gamma-function-reduction-relation}

$\Gamma(x) = (x-1) \cdot \Gamma(x)$

_Proof:_

The proof relies on integration by parts.  Let:

$$\begin{aligned}
u &= t^{x-1} \\
du &= (x - 1) \cdot t^{(x-2)} \\\\
v &= -e^{-t} \\
dv &= e^{-t} dt 
\end{aligned}$$

Integration by parts yields:

$$\begin{aligned}
\Gamma(x) &= \int\limits_0^{\infty}t^{x-1}e^{-t}dt \\
    &= u \cdot v - \int\limits_0^\infty v \cdot du \\
    &= \Big[t^{x-1} \cdot - e^{-t}\Big]_{t=0}^{t=\infty} - 
        \int\limits_0^\infty-e^{-t} \cdot (x-1)\cdot t^{(x-2)} dt \\
    &= -\Big[t^{x-1} \cdot e^{-t}\Big]_{t=0}^{t=\infty} - 
        (- (x - 1)) \int\limits_0^\infty e^{-t} \cdot t^{(x-2)} dt \\
^{[1]}    &= -0 +  
        (x - 1) \int\limits_0^\infty e^{-t} \cdot t^{(x-2)} dt \\
    &= (x - 1) \int\limits_0^\infty e^{-t} \cdot t^{((x-1)-1)} dt \\
    &= (x - 1) \int\limits_0^\infty t^{((x-1)-1)} \cdot e^{-t} dt \\
    &= (x - 1) \cdot \Gamma(x - 1) 
\end{aligned}$$

> 1. \@ref(gamma-function-reduction-lemma)

### Corollary

$$\Gamma(x) = \frac{1}{x} \cdot \Gamma(x + 1)$$

_Proof:_

Theorem \@ref(gamma-function-reduction-relation) establishes

$$ \Gamma(x) = (x - 1) \cdot \Gamma(x - 1)$$

Let $y = x + 1$.  Then

$$\begin{aligned}
\Gamma(y) &= (y - 1) \cdot \Gamma(y - 1) \\
\Rightarrow \Gamma(x + 1) 
    &= (x + 1 - 1) \cdot \Gamma(x + 1 - 1) \\
    &= x \cdot \Gamma(x) \\
\Rightarrow \frac{1}{x} \cdot \Gamma(x + 1) &= \Gamma(x) \\
\Rightarrow \Gamma(x) &= \frac{1}{x} \cdot \Gamma(x + 1)
\end{aligned}$$

This allows the recurrence relation to move toward $\Gamma(0)$ for any value of $x$.  Note, however, that $\Gamma(0)$ is undefined. Thus, solutions for the Gamma Function may be determined for positive integers, since $\Gamma(1)$ can be solved.  On the other hand, 
$\Gamma(-1)$ can not be solved, and the recurrence relation results in a zero denominator.  Hence, the Gamma Function is defined for all $x \in \mathbb{R}$ so long as $x \not\in \mathbb{Z^-}$


### Theorem:

$$\Gamma\Big(\frac{1}{2}\Big) = \sqrt{\pi}$$

_Proof:_

$$\begin{aligned}
\Gamma\Big(\frac{1}{2}\Big)
  &= \int\limits_0^\infty t^{-\frac{1}{2}} e ^{-t} dt \\
  &= \frac{2}{2} \int\limits_0^\infty t^{-\frac{1}{2}} e ^{-t} dt \\
  &= 2 \int\limits_0^\infty \frac{1}{2} \cdot t ^{-\frac{1}{2}} 
      e^{-(\sqrt{t})^2} dt \\
  &= 2 \int\limits_0^\infty \frac{1}{2} \cdot t ^{-\frac{1}{2}} 
      e^{-(\sqrt{t})^2} dt \\
^{[1]}  &= 2 \int\limits_0^\infty \frac{1}{2} \cdot x ^{-1} 
      e^{-x^2} \cdot 2\cdot x \ dx \\
  &= 2 \int\limits_0^\infty \frac{2x}{2x} e^{-x^2} dx \\
  &= 2 \int\limits_0^\infty e^{-x^2} dx \\
^{[2]}  &= 2 \cdot \frac{\sqrt{\pi}}{2} \\
  &= \sqrt{\pi} 
\end{aligned}$$

> 1. $x = \sqrt{t}$; $t = x^2$; and $dt = 2x dx$
> 2. Theorem \@ref(gaussian-integral-sqrt-pi)

### Theorem:

Let $c$ be a constant such that $c > 0$. Then 

$$
  \int_0^\infty t^x e^{-ct} \cdot dt = \frac{\Gamma(x+1)}{c^{x+1}}
$$

_Proof:_

$$\begin{aligned}
\int\limits_0^\infty t^x e^{-ct} dt \\
^{[1]}  &= \int\limits_0^\infty \big(\frac{y}{c}\big) ^ x e ^{-c \frac{y}{c}} \frac{dy}{c} \\
  &= \frac{1}{c^x} \cdot \frac{1}{c} 
      \int\limits_0^\infty y ^ x e ^{-y} dy \\
&= \frac{1}{c^{x + 1}}  
      \int\limits_0^\infty y ^ {(x+1)-1} e ^{-y} dy \\
^{[2]}  &= \frac{1}{c^{x + 1}} \cdot \Gamma(x + 1) \\
  &= \frac{\Gamma(x + 1)}{c^{x + 1}}
\end{aligned}$$

> 1. Let $y = ct$. Then $y = \frac{y}{c}$ and $dt = \frac{dy}{c}$. 
> 2. $\int\limits_0^\infty y^{(x+1)-1} e^{-y} dy$ satisfies the form of a Gamma function. \@ref(gamma-function-definition)

## References

* Pennsylvania State University, Elberly College of Science, STAT 414/415, https://onlinecourses.science.psu.edu/stat414/node/142
* Theodore Hatch Whitfield, Lecture Notes, E156 _Mathematical Foundations of Statistical Software_.


