# Geometric Series

## Series Starts at $k = 1$

A Geometric Series is a series of the form $\sum\limits_{k=1}^{\infty}ar^{k-1}$ 
where $a\neq 0,\ r\neq 0,1$.  Expanding the series gives $\sum\limits_{k=1}^{\infty}ar^{k-1}=a+ar+ar^2+ar^3+\cdots$.


### Partial and Infinite Summations {#geometric-series-partial-and-infinite-summations}

Let $S_k$ denote the sum of a series over $k$ terms (or the $k^{th}$ partial sum).  For the Geometric Series\\

$$\begin{aligned}
S_k
	&= \sum\limits_{k=1}^{k}ar^{k-1} \\
	&= a + ar + ar^2 + ar^3 + \cdots + ar^{k-1} \\
  &= ar^0 + ar^2 + ar^2 + \cdots + ar^{k-1} \\
	&= a + ar + ar^2 + \cdots + ar^{k-1}
\end{aligned}$$

Notice that $rS_k = ar + ar^2+ a r^3 + \cdots + ar^k$.  So

$$\begin{aligned}
S_k - rS_k
	&= (a + ar + \cdots + ar^{k-1}) - (ar + ar^2 + \cdots + ar^k) \\
  &= a + ar - ar + ar^2 - ar^2 + \cdots + ar^{k-2} - ar^{k-2} + ar^{k-1} - ar^{k-1} - ar^k \\
  &= a - ar^k
\end{aligned}$$

Observing that $S_k - rS_k = S_k(1 - r)$, we may conclude

$$\begin{aligned} 
S_k(1-r) 
  &= S_k - rS_k \\
	&= a - ar^k \\
\Rightarrow S_k &= \frac{a-ar^k}{1-r}
\end{aligned}$$



### Proofs of Convergence

$\sum\limits_{k=1}^{\infty}ar^{k-1}$ converges when $|r|<1$ and diverges when $|r|>1$.

_Proof:_

Recall that the $k^{th}$ partial sum of the Geometric Series is 

$$
S_k 
	= \frac{a-ar^k}{1-r}
$$

And let $S$ denote the sum of the infinite series, i.e. the sum as$k\rightarrow\infty$.

_Case 1:_ $|r|<1$

$$\begin{aligned}
S
	&= \lim\limits_{k\rightarrow\infty}S_k \\
	&=  \lim\limits_{k\rightarrow\infty} \frac{a-ar^k}{1-r} \\
  &= \frac{a-\lim\limits_{k\rightarrow\infty}ar^k}{1-r} \\
	&= \frac{a}{1-r}
\end{aligned}$$

So $\sum\limits_{k=1}^{\infty}ar^{k-1}$ converges when $|r|<1$ and $S=\frac{a}{1-r}$


_Case 2:_ $|r|>1$

$$\begin{aligned}
S
	&= \lim\limits_{k\rightarrow\infty}S_k \\
	&= \lim\limits_{k\rightarrow\infty} \frac{a-ar^k}{1-r} \\
  &= \frac{a-\lim\limits_{k\rightarrow\infty}ar^k}{1-r} \\
	&= \frac{a-\infty}{1-r}
\end{aligned}$$

So $\sum\limits_{k=1}^{\infty}ar^{k-1}$ diverges whern $|r|>1$.


## Series Starts at $k = 0$

A Geometric Series is a series of the form $\sum\limits_{k=0}^{\infty}ar^{k}$ 
where $a\neq 0,\ r\neq 0,1$.  Expanding the series gives $\sum\limits_{k=0}^{\infty}ar^{k}=a+ar+ar^2+ar^3+\cdots$.

### Partial and Infinite Summations {#geometric-series-partialk0-and-infinite-summations}

Let $S_k$ denote the sum of a series over $k$ terms (or the $k^{th}$ partial sum).  For the Geometric Series\\

$$\begin{aligned}
S_k
	&= \sum\limits_{k=0}^{n}ar^{k} \\
	&= a + ar + ar^2 + ar^3 + \cdots + ar^{k} \\
  &= ar^0 + ar^2 + ar^2 + \cdots + ar^{k} \\
	&= a + ar + ar^2 + \cdots + ar^{k}
\end{aligned}$$

Notice that $rS_k = ar + ar^2+ a r^3 + \cdots + ar^k$.  So

$$\begin{aligned}
S_k - rS_k
	&= (a + ar + \cdots + ar^{k}) - (ar + ar^2 + \cdots + ar^{k+1}) \\
  &= a + ar - ar + ar^2 - ar^2 + \cdots + ar^{k-1} - ar^{k-1} + ar^k + ar^k - ar^{k + 1}\\
  &= a - ar^{k+1}
\end{aligned}$$

Observing that $S_k - rS_k = S_k(1 - r)$, we may conclude

$$\begin{aligned} 
S_k(1-r) 
  &= S_k - rS_k \\
	&= a - ar^{k+1} \\
\Rightarrow S_k &= \frac{a-ar^{k+1}}{1-r}
\end{aligned}$$

### Proofs of Convergence

$\sum\limits_{k=0}^{\infty}ar^{k}$ converges when $|r|<1$ and diverges when $|r|>1$.

_Proof:_

Recall that the $k^{th}$ partial sum of the Geometric Series is 

$$
S_k 
	= \frac{a-ar^{k+1}}{1-r}
$$

And let $S$ denote the sum of the infinite series, i.e. the sum as$k\rightarrow\infty$.

_Case 1:_ $|r|<1$

$$\begin{aligned}
S
	&= \lim\limits_{k\rightarrow\infty}S_k \\
	&=  \lim\limits_{k\rightarrow\infty} \frac{a-ar^{k+1}}{1-r} \\
  &= \frac{a-\lim\limits_{k\rightarrow\infty}ar^{k+1}}{1-r} \\
	&= \frac{a}{1-r}
\end{aligned}$$

So $\sum\limits_{k=1}^{\infty}ar^{k}$ converges when $|r|<1$ and $S=\frac{a}{1-r}$


_Case 2:_ $|r|>1$
$$\begin{aligned}
S
	&= \lim\limits_{k\rightarrow\infty}S_k \\
	&= \lim\limits_{k\rightarrow\infty} \frac{a-ar^{k+1}}{1-r} \\
  &= \frac{a-\lim\limits_{k\rightarrow\infty}ar^{k+1}}{1-r} \\
	&= \frac{a-\infty}{1-r}
\end{aligned}$$

So $\sum\limits_{k=1}^{\infty}ar^{k-1}$ diverges whern $|r|>1$.

