--- 
title: "It Can Be Shown"
subtitle: "Notes on Statistical Theory"
author: "Benjamin Nutter"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: Biblio.bib
biblio-style: "apalike"
link-citations: yes
github-repo: nutterb/ItCanBeShown
nocite: | 
  @Hogg2005a, @Law2000a, @Wacke2002a
description: "Notes on the Development of Statistical Theory"
header-includes:
- \usepackage{amssymb} 
- \usepackage{arydshln} 
- \usepackage{caption} 
- \usepackage{graphicx} 
- \usepackage{hhline} 
- \usepackage{longtable} 
- \usepackage{multirow} 
- \usepackage[dvipsnames,table]{xcolor} 
- \allowdisplaybreaks
---

```{r, warning = FALSE, message = FALSE, echo = FALSE}
library(dplyr)
library(ggplot2)
library(magrittr)
library(pixiedust)
library(RColorBrewer)
library(StudyPlanning)
library(tidyr)

palette <- brewer.pal(9, "PRGn")
pallette_green <- rev(brewer.pal(7, "Greens")[3:5])
```



# Introduction

There is one phrase that makes me cringe every time I see it.  It's a phrase that embodies feelings of frustration, inadequacy, and failure to understand.  That phrase:

> It can be shown

Everytime I read that phrase, I would look at the subsequent result and think "Really? It can?"

This book is a collection of notes that I've put together to avoid having to feel that way in the future.  It is, essentially, a collection of definitions and proofs that have helped me understand and apply mathematical and statistical theory.  Most imporantly, it spells even the smallest steps along each development so that I don't have to worry about solving it again in the future.

You won't find much in the way of application.  There are no exercises.  There is only minimal explanation.  My intent is to show development of statistical theory and nothing else. 
