# Integration: Techniques and Theorems

## Elementary Theorems

### Integration of Even Functions about Zero {#integration-even-function-about-zero}

Suppose $f$ is an integratable function, and let $F(x)=\int\limits_{0}^{x_0}f(x)dx$.

Then $\int\limits_{-x_0}^{0}f(x)dx=\int\limits_{0}^{x_0}f(x)dx$ 
if and only if $f$ is an even function.\\

_Proof:_

First, let $f$ be an even function.  Then, by Theorem \@ref(derivatives-and-anti-derivatives-of-even-functions), the anti-derivative $F$ is an odd function.

$$\begin{aligned}
\int\limits_{-x_0}^{0}f(x)dx 
	      &= F(0) - F(-x_0) \\
	      &= F(0) + F(x_0) \\
^{[1]}	&= F(x_0)  \\
\\
\\
\int\limits_{0}^{x_0}f(x)dx 
	      &= F(x_0) - F(0) \\
	      &= F(x_0)
\end{aligned}$$

> 1. $F(0)=\int\limits_{0}^{0}f(x)dx=0$.

So 
$$\begin{aligned} 
\int\limits_{-x_0}^{0}f(x)dx
	&= F(x_0) \\
	&= \int\limits_{0}^{x_0}f(x)dx
\end{aligned}$$

Now suppose 

$$
\int\limits_{-x_0}^{0}f(x)dx
	= \int\limits_{0}^{x_0}f(x)dx
$$ 

Then

$$\begin{aligned}
\int\limits_{-x_0}^{0}f(x)dx
	&= F(0) - F(-x_0) \\
	&= -F(-x_0)
\end{aligned}$$

and

$$\begin{aligned} 
\int\limits_{0}^{x_0}f(x)dx
	= F(x_0) - F(0) \\
	= F(x_0)
\end{aligned}$$

So 
$$\begin{aligned}
-F(-x_0)          	&= F(x_0) \\
\Rightarrow F(-x_0) &= -F(x_0)
\end{aligned}$$

This satisfies the definition of an odd function.  So by Theorem \@ref(derivatives-and-anti-derivatives-of-odd-functions), $f$ must be an even function.


### Corollary

If $f$ is a continuous and even function and $t\in\Re$, then 

$$ \int\limits_{-t}^{t}f(x)dx = 2\int\limits_{0}^{t}f(x)dx $$

Furthermore, 

$$\int\limits_{-\infty}^{\infty}f(x)dx
	= 2\int\limits_{0}^{\infty}f(x)dx$$.

_Proof:_
Since $f(x)$ is even and by Theorem \@ref(integration-even-function-about-zero)

$$\begin{aligned}
\int\limits_{-t}^{0}f(-x)dx
	&= \int\limits_{-t}^{0}f(x)dx \\
	&= \int\limits_{0}^{t}f(x)dx
\end{aligned}$$

It follows that

$$\begin{aligned}
\int\limits_{-t}^{t}f(x)dx
	&= \int\limits_{-t}^{0}f(-x)dx + \int\limits_{0}^{t}f(x)dx \\
	&= \int\limits_{0}^{t}f(x)dx + \int\limits_{0}^{t}f(x)dx \\
	&= 2\int\limits_{0}^{t}f(x)dx
\end{aligned}$$

The second statement is proven by taking the limits as $t\rightarrow\infty$. 

### Integrals of Horizontal Translations

Let $x$ be any real number and $a,b,$ and $c$ be constants.  Also, let $f(x)$ be continuous on the interval $(a,b)$.  Then 

$$\int\limits_{a}^{b}f(x)dx = \int\limits_{a+c}^{b+c} f(x+c)dx$$

_Proof:_

The proof of this theorem is completed by applying a change of variable to 

$$\int\limits_{a}^{b}f(x)dx$$

We let 

$$\begin{aligned}
            y &= x+c \\
\Rightarrow x &= y-c
\end{aligned}$$

So $dx=dy$.

$$\begin{aligned}
x &= a   & \Rightarrow \ \ \ \   y &= a+c\\
x &= b   & \Rightarrow \ \ \ \   y &= b+c
\end{aligned}$$. 

Thus

$$\begin{aligned}
\int\limits_{a}^{b}f(x)dx
	&= \int\limits_{a+c}^{b+c}f(y)dy \\
	&= \int\limits_{a+c}^{b+c}f(x+c)dx
\end{aligned}$$

