# Real Number System

This chapter was prepared by Steve MacDonald\cite{McDonaa}.

## Historical Note

The first axiom system known in the history of mathematics was Euclid's aximoatic development of plane geometry.  Euclid's treatment began with some _primitive_ or _undefined_ terms and some assumed statements, which he called _axioms_ and _postulates_.  For Euclid an _axiom_ was a general "self-evident" truth, such as "The whole is greater than any of its parts" or "equals added to equals are equal," whereas a _postulate_ was an assumed statement about the relationships among the primitives of his system, such as "Two points determine exactly one line."  From these undefined terms and basic assumptions a whole body of other statements, called _theorems_ was deduced.  For centuries Euclidean Geometry, which was assumed to be the true description of physical reality, remained the only mathematical systems with such an axiomatic foundation.

Then in the nineteenth century, spurred by Lobatchevsky and others who discovered that by modifying the postulates another logically consistent geometry could be constructed, matematicians began to apply this deductive approach to other branches of mathematics.  Not only did this work do much to organize and clarify such familiar disciplines as number theory, analysis, and algebra, but it helped develop new areas of mathematics such as topology.  Note that today we do not make Euclid's distinction between _axiom_ and _postulate_, using the terms synonymously.

As an example of this deductive approach, we now want to give an axiomatic description of the real numbers system and thus place a logical foundation under many of the "rules" you learned in high school algebra.


## The Field of Real Numbers

### Definition: The Field of Real Numbers

The Field of Real Numbers is a set $\Re$ of objects called _numbers_ together with two well-defined binary operations, called _addition_, denoted by `+`, and _multiplication_, denoted by $\cdot$ or juxtaposition, satisfying the Field Axioms. (By well-defined, we mean that if $s=s^\prime$ and $t=t^\prime$, then $s+t=s^\prime + t^\prime$.)

### Field Axioms

1. (Closure for addition) For each pair $x,y,\in\Re$, there exists a unique object in $\Re$, called the _sum_ of $x$ and $y$ denoted by $x+y$.
2. (Associative law for addition) For all $x,y,z\in\Re,\ (x+y)=z=x+(y+z)$.
3. (Additive identity) There exists and object $0\in\Re$ such that for all $x\in\Re,\ x+0=x=0+x$.
4. (Additive inverse) For each $x\in\Re$, there exists some $y\in\Re$ such that $x+y=0=y+x$.  We will usually denote the additive inverse of $x$ by $-x$.
5. (Commutative law of addition) For all $x,y\in\Re,\ x+y=y+x$.
6. (Closure for multiplication) For each pair $,y,\in\Re$, there exists a unique object in $\Re$, called the _product_ of $x$ and $y$ and denoted by $x\cdot y$ or $xy$.
7. (Associative law of multiplication) For all $x,y,z\in\Re,\ x\cdot(y\cdot z)=(x\cdot y)\cdot z$.
8. (Multiplicative identity) There exists an object $1\in\Re$ such that for all $x\in\Re,\ 1\cdot x=x=x\cdot 1$.
9. (Multiplicative inverse) For each $x\in\Re$ such that $x\neq 0$, there exists an object $y\in\Re$ such that $x\cdot y=1=y\cdot x$.  We will usually denote the multiplicative inverse of $x$ by $x^{-1}$.
10. (Commutative law of multiplication) For all $x,y\in\Re,\ x\cdot y=y\cdot x$.
11. (Distributive law of multiplication over addition) For all $x,y,z\in\Re, x\cdot(y+z)=x\cdot y+x\cdot z$.
12. (Positive Elements) There exists a nonempty subset $\Re^+\subset\Re$ closed under $+$ and $\cdot$.  That is, for all $x,y\in\Re^+,\ x+y\in\Re$ and $x\cdot y\in\Re^+$.
13. (Trichotomy) For any $x\in\Re$, exactly one of these three cases holds: $x\in\Re^+,\ -x\in\Re^+$, or $x=0$.


### Definiton: Less Than (or Equal To) {#real-numbers-definition-less-than-equal-to}

Let $x,y\in\Re$.  We say that $x$ _is less than_ $y$, written $x<y$, provided $y+-x\in\Re^+$.  We say that $x$ is _less than or equal_ $y$ iff and only iff $x<y$ or $x=y$.  (Also, $x$ is said to be greater than $y$ if $y<x$.)

### Definition: Bounded Above (and Below)

A set $A$ of real numbers is said to be _bounded above_ if there exists some $b\in\Re$ such that $x\leq b,\ \forall x\in A$.  In this case, $b$ is called an _upper bound_ for $A$.  (Bounded below and lower bound are defined similarly.)

### Definition: Least Upper (and Lower) Bound

Let $A$ be a set of real numbers bounded above.  An element $\beta\in\Re$ is called the _least upper bound_, often written _lub_ for $A$ iff and only if

i. $\beta$ is an upper bound for $A$ and
ii. $\beta\leq b$ for every $b$ which is an upper bound for $A$. (A greatest lower bound is defined similarly.)


### Completeness Axiom

Every nonempty subset of $\Re$ having an upper bound has a least upper bound.

## Proof that the Field of Rationals is not Complete

Let $A=\left\{p\in Q^+|p^2<2\right\}$ and $B=\left\{p\in Q^+|p^2>2\right\}$.  

We claim that $A$ has no largest element and that $B$ has no smallest element; i.e., given that $p\in A$, we can find some $q\in A$ with $q>p$; and given any $p\in B$, we can find some $q\in B$ with $q<p$.

For any $p\in Q^+$, let 

$$q
  &=p-\frac{p^2-2}{p+2}
  &=\frac{p^2+2p-p^2+2}{p+2}
  &=\frac{2p+2}{p+2}$$  

Then 

$$q^2-2
  &=\frac{4p^2+8p+r-2p^2-8p-8}{(p+2)^2}
  &=\frac{2p^2-4}{(p+2)^2}
  &=\frac{2(p+2)}{(p+2)^2}$$
  
Now if $p\in A,\ p^2-2<0$, 

so $-\frac{p^2-2}{p+2}>0$, 

whence $q=p-\frac{p^2-2}{p+2}>p$.  

But $q^2-2=\frac{2(p^2-2)}{(p+2)^2}<0$ 

implies that $q^2<2$.  Thus $q\in A$ and $q>p$.

On the other hand, if $p\in B$, then $p^2-2>0$, 

so $q=p-\frac{p^2-2}{p+2}<p$.  

But $q^2-2=\frac{2(p^2-2)}{(p+2)^2}>0$ implies that $q\in B$.  

Here $q\in B$ and $q<p$.

Now it is clear that every member of $B$ is an upper bound for $A$, and every member of $A$ is a lower bound for set $B$.  It is also clear from the above demonstration that _among the rationals Q,_ the nonempty set $A$ has _no least upper bound_; and the nonempty set $B$ has _no greatest lower bound_ _among the rationals_ .  Therefore we have shown that the ordered field of rational numbers does not satisfy the conditions of the _Completeness Axiom_ .  Thus it is the _Completeness Axiom_ that distinguishes the ordered field of real numbers from the ordered field of rational numbers. 

## Preliminary Results in the Field of Real Numbers

### Theorem: Uniqueness of Identities

Identity elements are unique.

_Proof:_ 
Suppose $u \star a=a\star u=a$ and $e\star a=a\star e=a,\ \forall a\in\Re$.  Then $u=u\star e=e$.


### Theorem 2: Uniqueness of Inverses

If $\star$ is an associative operation, inverse elements for $\star$ are unique.

_Proof:_ 

Suppose $a\star a_1=a_1\star a=e$ and $a\star a_2=a_2\star a=e$, where $e$ is the identity element for the operation $\star$.

Then $a_1=a_1\star e=a_1\star(a\star a_2)=(a_1\star a)\star a_2)=e\star a_2=a_2$.


### Theorem: Left Cancellation Law

If $a$ has an inverse $a^\prime$ with respect to the associative operation $\star$, and $a\star b=a\star c$, then $b=c$.

_Proof:_

Suppose $a\star b=a\star c$.  Then 

$$
a^\prime\star(a\star b)             &= a^\prime\star(a\star c)\\
\Rightarrow(a^\prime\star a)\star b &= (a^\prime\star a)\star c\\
\Rightarrow e\star b                &= e\star c\\
\Rightarrow b                       &= c
$$


### Corollary: Right Cancellation

In the field $(\Re,+,\cdot),\ a+b=a+c\Rightarrow b=c$, and if $a\neq 0$ and $ab=ac$, then $b=c$.

_Proof:_ 
The Corollary is proved using commutativity and Left Cancellation.

### Lemma

$$-0=0$$.

_Proof:_

By axiom 4 $-0+0=0$.  Because 0 is the additive identity, $-0+0=-0$.  Therefore $-0=-0+0=0$. 


### Theorem

$\forall a\in\Re,\ a>0$ if and only if $a\in\Re^+$.

_Proof:_ 
Suppose $0<a$.  Then $a-0\in\Re^+$, but $a-0=a$, so $a\in\Re^+$.  Conversely, suppose $a\in\Re^+$.  Then $a-0=a\in\Re^+$, so $0<a$. 

### Theorem

$\forall x\in\Re,\ x\cdot 0=0$.

_Proof:_ 

$$
0 + x\cdot 0    &= x\cdot 0\\
                &= x\cdot(0+0)\\
                &= x\cdot 0 + x\cdot 0\\
  Rightarrow 0  &= x\cdot 0
$$

### Theorem

$\forall x\in\Re,\ -(-x)=x$.

_Proof:_

$-(-x)+(-x) = 0$ and $0 = x+(-x)$.  So

$$-(-x)+(-x) &= x+(-x)
  \Rightarrow -(-x) &= x $$


### Theorem {#real-numbers-theorem-4-9}

$$\forall x,y\in\Re,\ x\cdot(-y) = -(x\cdot y)=(-x)\cdot y$$

_Proof:_ 

$$
            x(-y)+xy  &= x(-y+y) 
                      &= x\cdot 0 \\
                      &= 0 \\
                      &= -(xy)+xy\\
\Rightarrow x(-y)+xy  &= -(xy)+xy\\
\Rightarrow x(-y)     &= -(xy)
$$

Similarly, 

$$
          (-x)y+xy &= (-x+x)y \\
                   &= 0\cdot y \\
                   &= 0 \\
                   &= -(xy)+xy\\
\Rightarrow (-x)y   &= -(xy)
$$

By transitivity, $(-x)y = -(xy) = x(-y)$. 

### Theorem {#real-numbers-theorem-4-10}

$$\forall x\in\Re,\ (-1)\cdot x=-x$$

_Proof:_ 

By Theorem \@ref(real-numbers-theorem-4-9)
$$
(-1)x &= -(1x)
      &= -x
$$


### Corollary {#real-numbers-theorem-4-11}

$$\forall x\in\Re,\ (-1)\cdot(-x)=x$$

_Proof:_ 

By \@ref(real-numbers-theorem-4-10)
$$(-1)(-x) =  -(-x) = x $$


### Theorem

$$\forall x\in\Re,\ (-x)(-x)=x\cdot x$$

_Proof:_

By Corollary \@ref(real-numbers-theorem-4-11)

$$(-x)(-x) 
  &= -(x(-x)) \\
  &= -((-x)x) \\
  &= -(-(x\cdot x)) \\
  &= (x\cdot x) \\
  &= x\cdot x
$$


### Theorem

Let $x$ and $y$ be any real numbers.  Then exactly one of the following is true:

i. $x>y$
ii. $x=y$
iii. $x<y$

_Proof:_

By Axiom 1, $\Re$ is closed under addition.  Thus, since $x,y\in\Re$ , $x+(-y)\in\Re$.   By Trichotomy, $x+(-y)\in\Re,\ -(x+(-y))\in\Re$, or $x+(-y)=0$.

$x+(-y)\in\Re\ \Rightarrow x>y$ (Definition \@ref(real-numbers-definition-less-than-equal-to))

$-(x+(-y))=(-x)+y\in\Re\ \Rightarrow x<y$ (Axiom 4)

$x+(-y)=0\ \Rightarrow x=y$ (Definition \@ref(real-numbers-definition-less-than-equal-to)). 


### Theorem

$$\forall a,b,c\in\Re,\ (a<b \wedge b<c)\Rightarrow a<c$$

_Proof:_ 

$$
              a<b &\wedge b<c \\ 
\Rightarrow b-a>0 &\wedge c-b>0 \\ 
\Rightarrow^{[1]}(b-a)+(c-b)>0 \\
\Rightarrow (c-b)+(b-a)>0 \\ 
\Rightarrow c-b+b-a>0 \\ 
\Rightarrow c-a>0 \\ 
\Rightarrow a<c 
$$

> 1. Axiom 12
\newpage
\subsection{Theorem}
\label{RealNumbers4.15}
$\forall a,b,c \in\Re,\ (a<b \ \Rightarrow a+c<b+c)$.\\
\\
_Proof:_ \\
\\
$a<b\ \Rightarrow\ b-a>0\\\\
\indent\Rightarrow b-c+c-a>0\ \Rightarrow b+c-a-c>0\\\\
\indent\Rightarrow (b+c)-(a+c)>0\ \Rightarrow a+c<b+c\ $\rule{.05in}{.05in}

\subsection{Theorem}
\label{RealNumbers4.16}
$\forall a,b,c\in\Re,\ (a<b\wedge c>0)\Rightarrow ac<bc$.\\
\\
_Proof:_ \\
\\
$a<b\Rightarrow b-a>0\  \Rightarrow\footnote[2]{Axiom 12 states that $\Re^+$ is closed under $\cdot$.}\ \ c(b-a)>0
	\Rightarrow\ bc-ac>0 \Rightarrow\ ac<bc$ \rule{.05in}{.05in}

\subsection{Theorem}
\label{RealNumbers4.17}
$\forall a,b,c\in\Re,\ (a<b\wedge c<0)\Rightarrow bc<ba$.\\
\\
_Proof:_\ \\
\\
$a<b\ \Rightarrow b-a>0\ \Rightarrow\footnote[3]{Theorem \ref{RealNumbers4.9}.}\ \ c(b-a)<0\ \Rightarrow bc-ba<0\ \Rightarrow bc<ba$.\rule{.05in}{.05in}

\subsection{Theorem}
\label{RealNumbers4.18}
If $a>b>0$ and $c>d>0$, then $ac>bd$.\\
\\
_Proof:_ \\
\\
$a>b\wedge c>d\ \Rightarrow a-b>0\wedge c-d>0\\ 
\indent\Rightarrow c(a-b)>0\wedge b(c-d)>0\ \Rightarrow ac-bc>0\wedge bc-bd>0\\
\indent\Rightarrow ac-bc+bc-bd>0\ \Rightarrow ac-bd>0\ \Rightarrow ac>bd$.\rule{.05in}{.05in}

\newpage
\subsection{Theorem}
\label{RealNumbers4.19}
In a field containing at least two elements, $1\in\Re^+$.\\
\\
_Proof:\rm \\
\\
Since in a field of more than one element, $1\neq 0$\footnote[1]{Theorem \ref{RealNumbers4.1}}\ we may assume that 1 is not 0.  Hence, by trichotomy, either $1\in\Re^+$ or $-1\in\Re^+$.  Suppose that $-1\in\Re^+$.  Then by closure $(-1)(-1)\in\Re^+$, but by Corollary \ref{RealNumbers4.11}, $(-1)(-1)=1$, so we now have both $-1\in\Re^+$ and $1\in\Re^+$, which is a contradiction, and hence it is impossible that $-1\in\Re^+$.  Therefore, $1\in\Re^+$.  \rule{.05in}{.05in}

\subsection{Theorem}
\label{RealNumbers4.20}
If $x>0$, then $x^{-1}>0$.\\
\\
_Proof:_ \\
\\
Since $x^{-1}$ has an inverse $x$, we know that $x^{-1}\neq 0$.  Hence, by Axiom 13, either $x^{-1}>0$ or $x^{-1}<0$.  Suppose $x^{-1}<0$.  Then $-x^{-1}\in\Re^+$, and since $\Re^+$ is closed under multiplication, $(-x^{-1})\cdot x\in\Re^+$.  Now by Theorem 7, $(-x^{-1})\cdot x=-(x^{-1}\cdot x)=-1$, so this would imply that $-1\in\Re^+$, in contradction to Theorem \ref{RealNumbers4.20}.  Since $x^{-1}<0$ must be be false, we conclude that $x^{-1}>0$ whenever $x>0$. \rule{.05in}{.05in}
