# Skew-Normal Distribution

## Preliminary Theorems

## Lemma: A Symmetry Theorem

Suppose the pdf of $X$, $f_X$ is symmetric about 0.  Let $w(\cdot)$ be any odd function.  Then the pdf of $Y=w(X)$, $f_Y$, is also symmetric about 0.

_Proof:_

Recall that if a pdf is symmetric about zero, it must demonstrate the property $P(T\leq t)=P(T\geq-t)$.  Since $f_X$ is symmetric, we know

$$\begin{aligned}
P(X\leq x)                            &= P(X\geq-x) \\
\Rightarrow P\big[ w(X)\leq w(x)\big] &= P\big[ w(X)\geq w(-x)\big]
	^{[1]}                              &= P\big[ w(X)\geq-w(x)\big] \\
                                      &= P(Y\leq y) \\
                            	        &= P(Y\geq-y)
\end{aligned}$$

Thus $f_Y$ is symmetric about 0.

> 1. By the definition of an odd function $f(-x)=-f(x)$.


## Lemma

Let $f_0$ be a one-dimensional probability density function symmetric over 0.

Also, let $G$ be a one dimensional probability distribution function such that $G^\prime$ exists and is a density function symmetric over 0. Then 

\[ 	\begin{array}{rl}
		f(x) = 2 f_0(x) G\big(w(x)\big) & (-\infty<x<\infty)\\
	\end{array}
\]

is a probability density function for any odd fuction $w(\cdot)$.\\

_Proof:_

Let $X\sim f_0$ and $Y\sim G^\prime$.

Now consider the random variable $X-w(Y)|Y$.

When $Y$ is fixed, $X-w(Y)$ is an odd function of $X$ and, by Lemma \ref{SkewNorm1.1}, $X-w(Y)$ is symmetric over 0. Thus,

$$\begin{aligned}
\frac{1}{2} 
                      	&= P\big(X-w(Y)\leq0|Y\big) \\
                ^{[1]}	&= E\Big[ P\big(X-w(Y)\leq0|Y\big) \Big] \\
\Rightarrow \frac{1}{2} &= E\big[ P\big( X\leq w(Y)|Y\big) \big]\\
\Rightarrow \frac{1}{2} &= \int\limits_{-\infty}^{\infty} P\big(X \leq w(Y)|Y\big) p(x) dx\\
\Rightarrow \frac{1}{2} &= \int\limits_{-\infty}^{\infty} G\big( w(Y) \big) f_0(x)dx\\
\Rightarrow 1           &= 2 \int\limits_{-\infty}^{\infty} f_0(X) G\big( w(Y) \big) dx
\end{aligned}$$

So $f(x) = 2 f_0(x)G\big(w(y)\big)$ is a valid density function for all $x,\ x\in\Re$. 

> 1. The expected value of $P(X\leq 0)=\frac{1}{2}$ when $X$ is distributed symmetric over 0.


## Expected Values
$$\begin{aligned}
E(X)
	&= \int\limits_{-\infty}^{\infty} x \cdot 2 f(x) \Phi(\alpha x)dx \\
	&= 2 \int\limits_{-\infty}^{\infty} x f(x) \Phi(\alpha x)dx \\
  &= 2 \int\limits_{-\infty}^{\infty} x \frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{x^2}{2} \bigg\}
		\Bigg[ \int\limits_{-\infty}^{\alpha x} \frac{1}{\sqrt{s\pi}} 
			\exp\bigg\{ -\frac{t^2}{2} \bigg\}dt \Bigg]dx \\
  &= 2\int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x \frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{x^2}{2} \bigg\}
		\frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx \\
  &= \frac{2}{2\pi} \int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x \exp\bigg\{ -\frac{x^2}{2} \bigg\} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx \\
  &= \frac{1}{\pi} \int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x \exp\bigg\{ -\frac{x^2}{2} \bigg\} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx
\end{aligned}$$

But $\exp\bigg\{ -\frac{t^2}{2} \bigg\}$ cannot be integrated in closed form, so the solution must be found with numerical methods.

$$\begin{aligned}
E(X^2)
	&= \int\limits_{-\infty}^{\infty} x^2 \cdot 2 f(x) \Phi(\alpha x)dx \\
	&= 2 \int\limits_{-\infty}^{\infty} x^2 f(x) \Phi(\alpha x)dx \\
  &= 2 \int\limits_{-\infty}^{\infty} x^2 \frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{x^2}{2} \bigg\}
		\Bigg[ \int\limits_{-\infty}^{\alpha x} \frac{1}{\sqrt{s\pi}} 
			\exp\bigg\{ -\frac{t^2}{2} \bigg\}dt \Bigg]dx \\
  &= 2\int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x^2 \frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{x^2}{2} \bigg\}
		\frac{1}{\sqrt{2\pi}} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx \\
  &= \frac{2}{2\pi} \int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x^2 \exp\bigg\{ -\frac{x^2}{2} \bigg\} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx \\
  &= \frac{1}{\pi} \int\limits_{-\infty}^{\infty} \int\limits_{-\infty}^{\alpha x}
		x^2 \exp\bigg\{ -\frac{x^2}{2} \bigg\} \exp\bigg\{ -\frac{t^2}{2} \bigg\} dt dx
\end{aligned}$$

But $\exp\bigg\{ -\frac{t^2}{2} \bigg\}$ cannot be integrated in closed form, so the solution must be found with numerical methods.



## Estimation of $\lambda$
Using the Moment Generating Function, it was shown that the skew of the Skew-Normal distribution can be calculated as
\[
S=sign(\lambda) \bigg(2 - \frac{\pi}{2}\bigg) 
		\Bigg(\frac{\lambda^2}
			{\frac{pi}{2}+(\frac{pi}{2}-1)\lambda^2}\Bigg)^{\frac{3}{2}}
\]

where $S$ denotes the skew of the distribution.  Given a value of skew for the distribution, a link can be made back to $\lambda$.  We begin by noticing that the following process is identical regardless of the sign of $\lambda$.  It is presented here as if $\lambda>0$

$$\begin{aligned}
S
	&= \bigg( 2-\frac{\pi}{2} \bigg)
		\Bigg( \frac{\lambda^2} {\frac{\pi}{2}+\big(\frac{\pi}{2}-1\big)
			\lambda^2} \Bigg)^{3/2} \\
\Rightarrow \bigg( \frac{S}{2-\frac{\pi}{2}} \bigg)
		&= \Bigg( \frac{\lambda^2} {\frac{\pi}{2}+\big(\frac{\pi}{2}-1\big)
			\lambda^2} \Bigg)^{3/2} \\
\Rightarrow \bigg( \frac{S}{2-\frac{\pi}{2}} \bigg)^{2/3}
		&= \Bigg( \frac{\lambda^2} {\frac{\pi}{2}+\big(\frac{\pi}{2}-1\big)
			\lambda^2} \Bigg) \\
\Rightarrow T 
		&= \Bigg( \frac{\lambda^2} {\frac{\pi}{2}+\big(\frac{\pi}{2}-1\big)
			\lambda^2} \Bigg) \\
\Rightarrow \bigg( \frac{\pi}{2} + \Big(\frac{\pi}{2}-1\Big) \lambda^2 \Bigg)T
		&= \lambda^2 \\
\Rightarrow \frac{\pi}{2}T + \Big( \frac{\pi}{2}-1 \Big) \lambda^2 T
		&= \lambda^2 \\
\Rightarrow \frac{\pi}{2}T
		&= \lambda^2 - \Big( \frac{\pi}{2}-1 \Big) \lambda^2 T \\
\Rightarrow \frac{\pi}{2}T
		&= \lambda^2 \bigg(1 - \Big( \frac{\pi}{2}-1 \Big) T \bigg) \\
\Rightarrow \lambda^2
		&= \frac{ \frac{\pi}{2}T }
			{ 1-\Big( \frac{\pi}{2}-1 \Big) T } \\
\Rightarrow \lambda^2
		&=  \frac{ \frac{\pi}{2} \Big( \frac{S}{2-\frac{\pi}{2}} \Big)^{2/3} }
			{ 1-\Big( \frac{\pi}{2}-1 \Big) \frac{S}{2-\frac{\pi}{2}} \bigg)^{2/3}} \\
\Rightarrow \lambda
		&= \frac{ \sqrt{\frac{\pi}{2}} \Big( \frac{S}{2-\frac{\pi}{2}} \Big)^{1/3} }
			{ \sqrt{ 1-\Big( \frac{\pi}{2}-1 \Big) 
				\frac{S}{2-\frac{\pi}{2}} \bigg)^{2/3}} }
\end{aligned}$$
				
> 1. Let $T=\big( \frac{S}{2-\frac{\pi}{2}} \big)^{2/3}$

This equation is only defined for certain values of $S$.  In particular, $S$ cannot be a number such that the denominator is 0, nor can the that which appears under the radical be negative.  These two restrictions can be collapsed, and the equation is defined so long as

$$\begin{aligned}
1-\Big( \frac{\pi}{2}-1 \Big) \bigg(\frac{S}{2-\frac{\pi}{2}}\bigg)^{2/3} > 0 \\
\Rightarrow 1 
		> \Big( \frac{\pi}{2}-1 \Big) \bigg(\frac{S}{2-\frac{\pi}{2}}\bigg)^{2/3} \\
\Rightarrow \Big( \frac{\pi}{2}-1 \Big)^{-1}
		> \bigg( \frac{S}{2-\frac{\pi}{2}} \bigg)^{2/3} \\
\Rightarrow \frac{ \Big( 2-\frac{\pi}{2} \Big)^{2/3} }
			{ \frac{\pi}{2}-1 }
		> S^{2/3} \\
\Rightarrow \frac{ 2-\frac{\pi}{2} }
			{ \Big( \frac{\pi}{2}-1 \Big)^{3/2} }
		> S \\
\Rightarrow -.9952 < S < .9952
\end{aligned}$$

We notice that the endpoints of this interval are approximations.  Ideally, the interval would span from -1 to 1, as most estimators of skew provide a value in that interval--values close to negative one denoting a strong left skew; values close to one denoting a strong right skew; 0 denoting perfect symmetry.  Although this relationship is not perfect, it is quite close to what we would like, and can be practically implemented.

