---
title: "It Can Be Shown"
author: "Benjamin Nutter"
header-includes:
  - \usepackage{color}
  - \usepackage{chngcntr}
  - \counterwithout{section}{chapter}
  - \renewcommand{\chaptername}{}
  - \renewcommand{\thechapter}{}
  - \usepackage{pifont}
  - \renewcommand\thefootnote{\ding{\numexpr171+\value{footnote}}}
output:
  html_document:
    fig_caption: no
    number_sections: no
    toc: yes
documentclass: book
---
```{r, echo=FALSE}
library(ggplot2)
library(RColorBrewer)
greens.pal <- rev(brewer.pal(9, "Greens"))
```

# Probability Distributions
* [The Bernoulli Distribution](html_files/Bernoulli.html)
    * [Probability Mass Function](html_files/Bernoulli.html#probability-mass-function)
    * [Cumulative Distribution Function](html_files/Bernoulli.html#cumulative-distribution-function)
    * [Expected Values](html_files/Bernoulli.html#expected-values)
    * [Moment Generating Function](html_files/Bernoulli.html#moment-generating-function)
    * [Theorems for the Bernoulli Distribution](html_files/Bernoulli.html#theorems-for-the-bernoulli-distribution)
        * [Validity of the Distribution](html_files/Bernoulli.html#validity-of-the-distribution)
        * [Sum of Bernoulli Random Variables](html_files/Bernoulli.html#sum-of-bernoulli-random-variables)


* [The Binomial Distribution](html_files/BinomialDistribution.html)
    * [Probability Mass Function](html_files/BinomialDistribution.html#probability-mass-function)
    * [Cumulative Distribution Function](html_files/BinomialDistribution.html#cumulative-distribution-function)
    * [Expected Values](html_files/BinomialDistribution.html#expected-values)
    * [Moment Generating Function](html_files/BinomialDistribution.html#moment-generating-function)
    * [Maximum Likelihood Estimator](html_files/BinomialDistribution.html#maximum-likelihood-estimator)
        * [Likelihood Function](html_files/BinomialDistribution.html#likelihood-function)
        * [Log-likelihood Function](html_files/BinomialDistribution.html#log-likelihood-function)
        * [MLE for $p$](html_files/BinomialDistribution.html#mle-for-p)
    * [Theorems for the Binomial Distribution](html_files/BinomialDistribution.html#theorems-for-the-binomial-distribution)
        * [Validity of the Distribution](html_files/BinomialDistribution.html#validity-of-the-distribution)
        * [Sum of Binomial Random Variables](html_files/BinomialDistribution.html#sum-of-binomial-random-variables)
        * [Sum of Bernoulli Random Variables](html_files/BinomialDistribution.html#sum-of-bernoulli-random-variables)


* [The Chi-Square Distribution](html_files/ChiSquareDistribution.html)
    * [Probability Distribution Function](html_files/ChiSquareDistribution.html#probability-distribution-function)
    * [Cumulative Distribution Function](html_files/ChiSquareDistribution.html#cumulative-distribution-function)
    * [Expected Values](html_files/ChiSquareDistribution.html#expected-values)
    * [Moment Generating Function](html_files/ChiSquareDistribution.html#moment-generating-function)
    * [Maximum Likelihood Function](html_files/ChiSquareDistribution.html#maximum-likelihood-function)
        * [Likelihood Function](html_files/ChiSquareDistribution.html#likelihood-function)
        * [Log-likelihood Function](html_files/ChiSquareDistribution.html#log-likelihood-function)
        * [MLE for $\mathbf{\nu}$](html_files/ChiSquareDistribution.html#mle-for-mathbfnu)
    * [Theorems for the Chi-Square Distribution](html_files/ChiSquareDistribution.html#theorems-for-the-chi-square-distribution)
        * [Validity of the Distribution](html_files/ChiSquareDistribution.html#validity-of-the-distribution)
        * [Sum of Chi-Square Random Variables](html_files/ChiSquareDistribution.html#sum-of-chi-square-random-variables)
        * [Square of a Standard Normal Random Variable](html_files/ChiSquareDistribution.html#square-of-a-standard-normal-random-variable)


\chapter{ The Exponential Distribution}
\chapter{ The Gamma Distribution}
\chapter{ The Geometric Distribution}
\chapter{ The Hypergeometric Distribution}
\chapter{ The Multinomial Distribution}
\chapter{ The Normal Distribution}
\chapter{ The Poisson Distribution}
\chapter{ The Skew-Normal Distribution}
\chapter{ The Uniform Distribution}
\chapter{ The Weibull Distribution}

# Frequentist Hypothesis Testing

\chapter{ Mantel-Haenszel Test}

# Supplemental Subjects

\chapter{ Chebychev's Theorem}
\chapter{ Combinations}
\chapter{ The Correlation Coefficient}
\chapter{ Covariance}
\chapter{ Experimental Designs}
\chapter{ Moments and Moment Generating Functions}
\chapter{ Summation}
\chapter{ The Method of Transformations}
\chapter{ Variance Paramter}

# Non-Statistical Proofs

\chapter{ The Binomial Theorem}
* [Functions](html_files/Functions.html)
    * [Fundamental Concepts and Definitions](html_files/Functions.html#fundamental-concepts-and-definitions)
        * [Function Operations](html_files/Functions.html#function-operations)
    * [Identities and Inverses](html_files/Functions.html#identities-and-inverses)
    * [Odd and Even Functions](html_files/Functions.html#odd-and-even-functions)
    * [Theorems for Functions](html_files/Functions.html#theorems-for-functions)
        * [Operations on Even Functions](html_files/Functions.html#operations-on-even-functions)
        * [Operations on Odd Functions](html_files/Functions.html#operations-on-odd-functions)
        * [Operations on an Odd and Even Function](html_files/Functions.html#operations-on-an-odd-and-even-function)
        * [Derivatives and Anti-derivatives of Odd Functions](html_files/Functions.html#derivatives-and-anti-derivatives-of-odd-functions)
        * [Derivatives and Anti-derivatives of Even Functions](html_files/Functions.html#derivatives-and-anti-derivatives-of-even-functions)

\chapter{ The Geometric Series}
\chapter{ Integraion: Techniques and Theorems}
\chapter{ Logarithmic and Exponential Functions}
\chapter{ The Real Number System}


